-- =====================================================================
-- 06 — PII wall smoke test (docs/06 §4b, release gate 🚦)
--
-- Proves, against a freshly migrated database, that the item-67 rules are
-- enforced by Postgres and not by application code:
--   * regulars_app holds ZERO privileges on schema pii
--   * the only doors are pii.customer_public and pii.reveal_identity()
--   * a vendor cannot see a name or phone until that customer ordered with them
--   * every reveal is audited
--   * the WhatsApp ledger's phone (and messages.raw) are column-revoked
--   * regulars_ml can never reach pii
--   * browse telemetry: IST stamping, append-only, replay-safe ingest
--
-- Run:  psql "$DATABASE_DIRECT_URL" -f 06-pii-wall-smoke.sql
-- Every line marked EXPECT must hold. Run it in CI after migrations.
-- =====================================================================
\set ON_ERROR_STOP off

-- ---------- seed (users.vendor_id is required for owners, so seed as admin) ----------
INSERT INTO app.users (id, name, email, password_hash, role)
VALUES ('11111111-1111-1111-1111-111111111111','Seed','seed@x.test','x','super_admin');
INSERT INTO app.vendors (id, name, owner_user_id, contact_phone, contact_email, signup_door) VALUES
 ('aaaaaaaa-0000-0000-0000-000000000001','Cafe A','11111111-1111-1111-1111-111111111111','+919000000001','a@x.test','self'),
 ('bbbbbbbb-0000-0000-0000-000000000002','Cafe B','11111111-1111-1111-1111-111111111111','+919000000002','b@x.test','self');
INSERT INTO pii.customers (id, phone, name)
VALUES ('cccccccc-0000-0000-0000-000000000001','+919876543210','Rahul');
INSERT INTO app.customer_profiles (vendor_id, customer_id, phone_hash, source)
SELECT x.v, c.id, c.phone_hash, 'qr_order' FROM pii.customers c,
  (VALUES ('aaaaaaaa-0000-0000-0000-000000000001'::uuid),('bbbbbbbb-0000-0000-0000-000000000002'::uuid)) x(v)
WHERE c.id='cccccccc-0000-0000-0000-000000000001';

\echo '\n1. phone_hash is generated by the DB — the app never computes or stores it'
SELECT phone, left(phone_hash,24)||'…' AS phone_hash FROM pii.customers;   -- EXPECT: a hash

\echo '\n2. regulars_app privileges on pii tables'
SELECT t.tablename, p.priv FROM pg_tables t, (VALUES ('SELECT'),('INSERT'),('UPDATE'),('DELETE')) p(priv)
WHERE t.schemaname='pii' AND has_table_privilege('regulars_app','pii.'||t.tablename,p.priv);
                                                                            -- EXPECT: 0 rows

\echo '\n3. regulars_app reads the phone book directly'
SET ROLE regulars_app; SELECT phone FROM pii.customers; RESET ROLE;         -- EXPECT: permission denied

\echo '\n4. the open door — no phone, no name'
SET ROLE regulars_app; SELECT id, left(phone_hash,16)||'…' AS hash, order_count, status FROM pii.customer_public; RESET ROLE;

\echo '\n5. Cafe A asks for the name BEFORE any order'
BEGIN; SET ROLE regulars_app; SET LOCAL app.vendor_id='aaaaaaaa-0000-0000-0000-000000000001';
SELECT * FROM pii.reveal_identity('cccccccc-0000-0000-0000-000000000001'); ROLLBACK;
                                                                            -- EXPECT: ERROR CUSTOMER_NOT_REVEALED

\echo '\n6. Rahul places his first order at Cafe A (reveal is written in that transaction)'
UPDATE app.customer_profiles SET revealed_at=now(), display_name='Rahul'
WHERE vendor_id='aaaaaaaa-0000-0000-0000-000000000001';

\echo '\n7. Cafe A asks again'
BEGIN; SET ROLE regulars_app; SET LOCAL app.vendor_id='aaaaaaaa-0000-0000-0000-000000000001';
SELECT * FROM pii.reveal_identity('cccccccc-0000-0000-0000-000000000001'); RESET ROLE; COMMIT;
                                                                            -- EXPECT: Rahul, +919876543210

\echo '\n8. Cafe B never took an order from him'
BEGIN; SET ROLE regulars_app; SET LOCAL app.vendor_id='bbbbbbbb-0000-0000-0000-000000000002';
SELECT * FROM pii.reveal_identity('cccccccc-0000-0000-0000-000000000001'); ROLLBACK;
                                                                            -- EXPECT: ERROR CUSTOMER_NOT_REVEALED

\echo '\n9. every reveal is audited'
SELECT action, target_table, vendor_id FROM app.audit_logs WHERE action='customer.reveal';   -- EXPECT: exactly 1 row

\echo '\n10. WhatsApp ledger column grants'
SELECT 'conversations.phone' AS col, has_column_privilege('regulars_app','app.conversations','phone','SELECT') AS granted
UNION ALL SELECT 'conversations.status', has_column_privilege('regulars_app','app.conversations','status','SELECT')
UNION ALL SELECT 'messages.phone',        has_column_privilege('regulars_app','app.messages','phone','SELECT')
UNION ALL SELECT 'messages.raw',          has_column_privilege('regulars_app','app.messages','raw','SELECT')
UNION ALL SELECT 'messages.content_text', has_column_privilege('regulars_app','app.messages','content_text','SELECT');
                                                                            -- EXPECT: phone f, raw f, others t

\echo '\n11. regulars_ml can never reach pii'
SELECT has_schema_privilege('regulars_ml','pii','USAGE') AS ml_can_use_pii;  -- EXPECT: f

\echo '\n12. browse telemetry: anonymous visit, IST stamped by trigger'
INSERT INTO app.visitors (id) VALUES ('dddddddd-0000-0000-0000-00000000000f');
INSERT INTO app.browse_sessions (id, vendor_id, outlet_id, visitor_id, max_scroll_pct, item_view_count, outcome)
VALUES ('ffffffff-0000-0000-0000-00000000000f','aaaaaaaa-0000-0000-0000-000000000001',
        'aaaaaaaa-0000-0000-0000-0000000000ff','dddddddd-0000-0000-0000-00000000000f',75,3,'bounced');
SELECT outcome, max_scroll_pct, local_date, day_part, hour_local FROM app.browse_sessions;

\echo '\n13. beacon ingest writes the client timestamp, and a replay is a no-op'
INSERT INTO app.browse_events (browse_session_id, vendor_id, outlet_id, visitor_id, kind, seq, occurred_at)
VALUES ('ffffffff-0000-0000-0000-00000000000f','aaaaaaaa-0000-0000-0000-000000000001',
        'aaaaaaaa-0000-0000-0000-0000000000ff','dddddddd-0000-0000-0000-00000000000f','item_viewed',1,'2026-09-09T12:00:00Z');
INSERT INTO app.browse_events (browse_session_id, vendor_id, outlet_id, visitor_id, kind, seq, occurred_at)
VALUES ('ffffffff-0000-0000-0000-00000000000f','aaaaaaaa-0000-0000-0000-000000000001',
        'aaaaaaaa-0000-0000-0000-0000000000ff','dddddddd-0000-0000-0000-00000000000f','item_viewed',1,'2026-09-09T12:00:00Z');
                                                                            -- EXPECT: ERROR 23505 on the second
INSERT INTO app.browse_events (browse_session_id, vendor_id, outlet_id, visitor_id, kind, seq)
VALUES ('ffffffff-0000-0000-0000-00000000000f','aaaaaaaa-0000-0000-0000-000000000001',
        'aaaaaaaa-0000-0000-0000-0000000000ff','dddddddd-0000-0000-0000-00000000000f','item_viewed',2);
                                                                            -- EXPECT: ERROR not-null (no DEFAULT now(), by design)
SELECT count(*) AS rows_stored FROM app.browse_events;                      -- EXPECT: 1

\echo '\n14. browse_events is append-only'
UPDATE app.browse_events SET dwell_ms = 9999;                               -- EXPECT: ERROR append-only
